### ISSUE TITLE
Build package for trigger

### ISSUE THREAD

**Issue by web-vertalo** [Vertalo/freebsd-ports#3]
**Objective**
Build trigger as a FreeBSD package

**Acceptance Criteria**
How will we confirm that this work item is complete?
- [ ] Can build trigger under poudriere
- [ ] Can install via build server
- [ ] Build

**Tasks**
What will we do to complete this work item?
- [ ] Port trigger to FreeBSD
- [ ] Configure for poudriere
- [ ] Add to package list for build
